# OpenFOAM build dependencies (version via OPENFOAM_VERSION in make-config-user.mk)
brew "bash"
brew "open-mpi"
brew "libomp"
brew "adios2"
brew "boost"
brew "cmake"
brew "fftw"
brew "kahip"
brew "metis"
brew "cgal"
brew "scotch"
brew "flex"
brew "dylibbundler"
