#!/usr/bin/env bash
# Portable pack prefs: clean build-machine paths; wire bundled OpenMPI via
# official prefs.sys-openmpi (loaded from etc/bashrc → config.sh/mpi).
# Does not patch etc/bashrc — `source <prefix>/etc/bashrc` is enough at runtime.
set -euo pipefail

STAGE="${1:?stage prefix required}"
PREFS="${STAGE}/etc/prefs.sh"
BASHRC="${STAGE}/etc/bashrc"
PREFS_SYS_OPENMPI="${STAGE}/etc/config.sh/prefs.sys-openmpi"
BUNDLED='${WM_PROJECT_DIR}/lib'
MARKER='# Bundled runtime libraries (dist-native)'
MPI_MARKER='# Bundled OpenMPI relocation (dist-native)'

if [[ ! -f "${BASHRC}" ]]; then
  echo "[rewrite_openfoam_prefs] Missing ${BASHRC}" >&2
  exit 1
fi

sed_inplace() {
  if [[ "$(uname -s)" == "Darwin" ]]; then
    sed -i '' "$@"
  else
    sed -i "$@"
  fi
}

# Drop build-machine third-party paths from prefs (Homebrew / local prefixes).
if [[ -f "${PREFS}" ]]; then
  case "$(uname -s)" in
  Darwin)
    sed_inplace \
      -e '/\/opt\/homebrew\//d' \
      -e '/\/usr\/local\/opt\//d' \
      -e '/\/usr\/local\/Cellar\//d' \
      "${PREFS}"
    ;;
  Linux)
    sed_inplace \
      -e '/\/usr\/local\//d' \
      "${PREFS}"
    ;;
  esac
  if grep -qF "${MARKER}" "${PREFS}"; then
    awk -v marker="${MARKER}" '
      $0 == marker { skip=1; next }
      skip && /^export OPENFOAM_BUNDLED_LIB=/ { skip=0; next }
      skip { next }
      { print }
    ' "${PREFS}" >"${PREFS}.tmp"
    mv "${PREFS}.tmp" "${PREFS}"
  fi
fi

# Strip legacy dist-native patches previously appended to bashrc.
strip_bashrc_marker_block() {
  local marker="$1"
  if ! grep -qF "${marker}" "${BASHRC}"; then
    return 0
  fi
  awk -v marker="${marker}" '
    $0 == marker { skip=1; next }
    skip && /^fi$/ { skip=0; next }
    skip { next }
    { print }
  ' "${BASHRC}" >"${BASHRC}.tmp"
  mv "${BASHRC}.tmp" "${BASHRC}"
  echo "[rewrite_openfoam_prefs] Removed legacy bashrc block: ${marker}"
}

strip_bashrc_marker_block "${MARKER}"
strip_bashrc_marker_block "${MPI_MARKER}"

# Official hook: config.sh/mpi sources prefs.sys-openmpi, then
#   _foamAddPath $MPI_ARCH_PATH/bin  (lib/bin -> mpi-bin)
#   _foamAddLibAuto $MPI_ARCH_PATH   (lib/lib -> .  => libs on LD path)
if [[ -f "${STAGE}/lib/.bundle-stamp" ]]; then
  mkdir -p "$(dirname "${PREFS_SYS_OPENMPI}")"
  if [[ ! -e "${STAGE}/lib/bin" && -d "${STAGE}/lib/mpi-bin" ]]; then
    ln -sfn mpi-bin "${STAGE}/lib/bin"
  fi
  if [[ ! -e "${STAGE}/lib/lib" ]]; then
    ln -sfn . "${STAGE}/lib/lib"
  fi
  {
    echo '# Generated by rewrite_openfoam_prefs.sh for portable / Docker installs.'
    echo '# Loaded via etc/bashrc → config.sh/mpi (do not edit etc/bashrc).'
    echo "export MPI_ARCH_PATH=\"${BUNDLED}\""
    echo "export OPAL_PREFIX=\"${BUNDLED}\""
    echo "export OPAL_LIBDIR=\"${BUNDLED}\""
    echo "export PRTE_PREFIX=\"${BUNDLED}\""
    # -e rejects dangling Cellar links left by older cp -a packs.
    if [[ -e "${STAGE}/lib/share/openmpi" ]]; then
      echo "export OPAL_DATADIR=\"${BUNDLED}/share\""
      echo "export OPAL_PKGDATADIR=\"${BUNDLED}/share/openmpi\""
    fi
    mca_file="$(
      find "${STAGE}/lib/openmpi" \
        \( -name 'mca_*.so' -o -name 'mca_*.dylib' \) -type f 2>/dev/null \
        | head -1 || true
    )"
    if [[ -n "${mca_file}" ]]; then
      mca_rel="${mca_file#"${STAGE}/lib/"}"
      echo "export OMPI_MCA_mca_base_component_path=\"${BUNDLED}/$(dirname "${mca_rel}")\""
    fi
    echo 'export OMPI_MCA_reachable="${OMPI_MCA_reachable:-^netlink}"'
    echo 'export OMPI_MCA_btl_base_warn_component_unused="${OMPI_MCA_btl_base_warn_component_unused:-0}"'
  } >"${PREFS_SYS_OPENMPI}"
  echo "[rewrite_openfoam_prefs] Wrote ${PREFS_SYS_OPENMPI}"
elif [[ -f "${PREFS_SYS_OPENMPI}" ]] && grep -qF 'rewrite_openfoam_prefs.sh' "${PREFS_SYS_OPENMPI}"; then
  rm -f "${PREFS_SYS_OPENMPI}"
  echo "[rewrite_openfoam_prefs] Removed stale ${PREFS_SYS_OPENMPI}"
fi

echo "[rewrite_openfoam_prefs] Prefs ready; source etc/bashrc loads bundled when present"
